# Written by Ann-Marie Thompson 15.10.18

# Create flashcard dictionaries

halloween = {'Süßes oder Saures':'trick or treat',
             'naschen':'to eat sweets, to nibble',
             'einen Kürbis schnitzen':'to carve a pumpkin',
             'sich verkleiden':'to dress (oneself) up',
             'Streiche spielen':'to play pranks',
             'unheimlich':'eerie',
             'gruselig':'scary',
             'das Fest':'the feast, the celebration',
             'die Feier':'the celebration',
             'Allerheiligen':'All Saints',
             'der Kürbis':'the pumpkin',
             'ein Kostüm':'a costume',
             'eine Verkleidung':'a costume',
             'die Toten':'the dead',
             'das Spukhaus':'the haunted house',
             'das Geisterhaus':'the haunted house',
             'die Kerzen':'the candles',
             'die Geister':'the ghosts',
             'die Dekoration':'the decoration',
             'die Spinnweben':'the cobwebs',
             'die Süßigkeiten':'the sweets'}

birthdays = {'Zum Geburtstag viel Glück':'for the birthday much happiness',
             'Herzlichen Glückwunsch, liebe / lieber':'Happy Birthday, dear...',
             'Alles Liebe zum Geburstag':'Much love for the birthday',
             'Von Herzen alles Gute zum Geburstag':'all the best from the heart for the birthday',
             'Auch von mir nur das Beste zum Geburstag':'all the best for the birthday from me as well',
             'Hoch soll sie lebn, drei Mai hoch':'May she live high, three times high',
             'Viel Gesundheit, Glück und Zufriedenheit dem Geburstagkind':'Much health, happiness and contentment for the birthday child',
             'Alles Gute zum Geburstag für Sie':'All the best for the birthday for you (formal)',
             'Ich wünsche Ihnen ein gesundes und erfolgreiches neues Lebensjahr':'I wish you (formal) a healthy and successful new year of life',
             'Alles Gute zum Geburstag nachträglich':'Happy belated birthday',
             'Viel Glück und viel Segen':'much happiness and blessings',
             'Es lebe das Geburstagkind':'Long live the birthday child',
             'Viel Liebe und Freude fuer Dich':'Lots of love and joy for you'}

studies = {'der Abschluss, -**e':'degree',
           'das Diplom, -e':'degree, diploma',
           'das Abschlusszeugniss':'diploma',
           'der Dozent, -en':'college/uni instructor',
           'das Fach, -**er':'subject',
           'das Seminar, -e':'seminar',
           'das Stipendium, -en':'scholarship',
           'die Veranstaltung, -en':'class, course',
           'die Vorlesung, -en':'lecture',
           'die Architektur':'architecture',
           'die Biologie':'biology',
           'die Chemie':'chemistry',
           'die Fremdsprache, -n':'foreing language',
           'die Geschichte':'history',
           'die Informatik':'computer science',
           'die Kunst, -**e':'art',
           'die Literatur':'literature',
           'die Mathematik':'math',
           'die Medizin':'medicine',
           'die Naturewissenschaft, -en':'science',
           'die Physik':'physics',
           'die Psychologie':'psychology',
           'die Wirtschaft':'business',
           'belegen':'to take',
           'gehen':'to go',
           'lernen':'to study; to learn',
           'studieren':'to study; to major in',
           'das Café, -s':'café',
           'der Hörsaal':'lecture hall',
           'der Seminarraum, -raaume':'college/uni classroom',
           'die Sporthalle, -n':'gym'}

verbs = {'antworten':'to answer',
         'arbeiten':'to work',
         'bedeuten':'to mean, to signify',
         'beginnen':'to begin',
         'bekommen':'to become',
         'bestellen':'to order',
         'besuchen':'to visit',
         'bezahlen':'to pay',
         'bleiben':'to stay',
         'bringen':'to bring',
         'danken':'to thank',
         'denken':'to think',
         'finden':'to find',
         'fliegen':'to fly',
         'fragen':'to ask',
         'gehen':'to go',
         'hören':'to hear, to listen',
         'kaufen':'to buy',
         'kommen':'to come',
         'kosten':'to cost',
         'lieben':'to love',
         'machen':'to make, to do',
         'öffnen':'to open',
         'probieren':'to try (out)',
         'regnen':'to rain',
         'reisen':'to travel',
         'sagen':'to say',
         'schmecken':'to taste, to be tasty',
         'schreiben':'to write',
         'schwimmen':'to swim',
         'senden':'to send',
         'setzen':'to put, to set',
         'singen':'to sing',
         'spielen':'to play',
         'suchen':'to look for',
         'trinken':'to drink',
         'verstehen':'to understand',
         'warten':'to wait',
         'wohnen':'to live in',
         'zeigen':'to show'}

irregular_verbs = {'braten':'to fry',
                   'empfehlen':'to recommend',
                   'essen':'to eat',
                   'fahren':'to go',
                   'fallen':'to fall',
                   'fangen':'to catch',
                   'geben':'to give',
                   'helfen':'to help',
                   'lassen':'to allow',
                   'laufen':'to run',
                   'lesen':'to read',
                   'nehmen':'to take',
                   'schlafen':'to sleep',
                   'sehen':'to see',
                   'sprechen':'to speak',
                   'stehlen':'to steal',
                   'tragen':'to carry, to wear',
                   'treffen':'to hit, to meet',
                   'vergessen':'to forget',
                   'waschen':'to wash',
                   'werden':'to become',
                   'werfen':'to throw'}
list_of_dicts = [halloween, birthdays, studies, verbs, irregular_verbs]
string_list_of_dictionaries = ['halloween', 'birthdays', 'studies', 'verbs', 'irregular_verbs']
